version: "3.9"

services:
  app:
    build: ./app
    ports:
      - "8080:8080"
    env_file:
      - ./app/.env
    depends_on:
      - database
    command: sh -c "sleep 5 && uvicorn api:app --host 0.0.0.0 --port 8080 --log-level info"

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
