services:
  app:
    build: ./app
    ports:
      - "8080:8080"
    env_file:
      - ./app/.env
    depends_on:
      - database
      - rabbitmq

  worker:
    build: ./app
    command: ["python", "-u", "worker/consumer.py"]
    env_file:
      - ./app/.env
    depends_on:
      - rabbitmq
      - app

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rmuser
      RABBITMQ_DEFAULT_PASS: rmpassword
    ports:
      - "5672:5672"   # порт для приложений (app и worker)
      - "15672:15672" # веб-интерфейс RabbitMQ Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  database:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  rabbitmq_data:
